### ISSUE TITLE
QELAM: Students batch page opening issue

### ISSUE THREAD

**Issue by fakhruddin-vsbizz** [fakhruddin-vsbizz/qel-arabic-moallema#11]
Issue occurs when `batch_name` variable loads and sometimes does not load and throws this error:

Just need a look if `async await` works instead of `then` since `then` continues to execute the remaining function and executes after promise settles.

![WhatsApp Image 2023-02-11 at 14 49 21](https://user-images.githubusercontent.com/124787799/218251963-78389843-4db2-4cd4-8433-7e2de2dac795.jpg)

**Comment by somesh2001** [comment]
The issue arises because the detail is not defined when we are using it, so we have to add a check in order to resolve this error.

code - 

  if (detailStudent[0] && arr && detail[0]) {
    sheduleData = arr.filter(
      (sch) => sch.schedule.batchName === detail[0].batch_name
    );
  }
