### ISSUE TITLE
Batches in Admin: Students removed in backend, not removed in frontend

### ISSUE THREAD

**Issue by fakhruddin-vsbizz** [fakhruddin-vsbizz/qel-arabic-moallema#5]
@atif-vsbizz  the issue arises when the student added is removed. On the first time, it removes from UI, after that component is not removed.

**Comment by fakhruddin-vsbizz** [comment]
@somesh2001 you could look and provide help for the same

**Comment by somesh2001** [comment]
> @somesh2001 you could look and provide help for the same

Resolved this issue @fakhruddin-vsbizz 

1. Student can be removed from the front end (checked by removing multiple students)
2. Problem arises because the state is not updated whenever we remove the student, and hence the changes will not appear on the UI
